# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb9f6ff2ea484aa024c104b9fc336714ebc9b428be6f855eb522033abb99824986e805028d97e3ef1b78f82cfe10c8e10dd872e95222029494ca75b6bf95e97

test:
  secret_key_base: 5a4db1663de703f8b99fe41d6dfd0f4660de492689b47afece594553af2d514f2c67f82904447cf9a96f7ec588421de707cab16f8cbcfb9e51b2750d826cfcfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
